using System.Collections.Generic;
 using System.Collections.ObjectModel;
 using System.ComponentModel;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using SvgComposition.AttributeControls;
using SvgComposition.Controls;
using SvgComposition.Model;
using SvgCompositionTool.Dialogs;
 
namespace SvgComposition.ElementControls
{
public void CreateElement8619()
{
SvgElement el1 = CreateAnElement(true, el0, "lighttest", "", "svg",0);
SvgAttribute at1 = CreateAnAttribute(el1, "id", "lighttest", "", SvgAttributeType.Value, "px");
SvgAttribute at2 = CreateAnAttribute(el1, "width", "440", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at3 = CreateAnAttribute(el1, "height", "140", "", SvgAttributeType.LengthPercent, "px");
SvgElement el2 = CreateAnElement(false, el1, "", "No Light", "text",0);
SvgAttribute at4 = CreateAnAttribute(el2, "x", "60", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at5 = CreateAnAttribute(el2, "y", "22", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at6 = CreateAnAttribute(el2, "text-anchor", "middle", "", SvgAttributeType.Text, "px");
SvgElement el3 = CreateAnElement(false, el1, "", "", "circle",0);
SvgAttribute at7 = CreateAnAttribute(el3, "cx", "60", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at8 = CreateAnAttribute(el3, "cy", "80", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at9 = CreateAnAttribute(el3, "r", "50", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at10 = CreateAnAttribute(el3, "stroke", "#00ff00", "", SvgAttributeType.Color, "px");
CreateAColor(at10, 0, 255, 0, 255, 0);
SvgAttribute at11 = CreateAnAttribute(el3, "stroke-opacity", "1.0", "", SvgAttributeType.Value, "px");
SvgAttribute at12 = CreateAnAttribute(el3, "stroke-width", "1", "", SvgAttributeType.LengthPercent, "px");
SvgAttribute at13 = CreateAnAttribute(el3, "fill", "#00ff00", "", SvgAttributeType.Color, "px");
CreateAColor(at13, 0, 255, 0, 255, 0);
SvgAttribute at14 = CreateAnAttribute(el3, "fill-opacity", "1.0", "", SvgAttributeType.Value, "px");
SvgElement el4 = CreateAnElement(false, el1, "", "fePointLight", "text",0);
SvgAttribute at15 = CreateAnAttribute(el4, "x", "170", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at16 = CreateAnAttribute(el4, "y", "22", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at17 = CreateAnAttribute(el4, "text-anchor", "middle", "", SvgAttributeType.Text, "px");
SvgElement el5 = CreateAnElement(false, el1, "lightMe1", "", "filter",0);
SvgAttribute at18 = CreateAnAttribute(el5, "id", "lightMe1", "", SvgAttributeType.Value, "px");
SvgElement el6 = CreateAnElement(false, el5, "", "", "feDiffuseLighting",0);
SvgAttribute at19 = CreateAnAttribute(el6, "in", "SourceGraphic", "", SvgAttributeType.Text, "px");
SvgAttribute at20 = CreateAnAttribute(el6, "result", " light", "", SvgAttributeType.Value, "px");
SvgAttribute at21 = CreateAnAttribute(el6, "lighting-color", "#ffffff", "", SvgAttributeType.Color, "px");
CreateAColor(at21, 0, 255, 255, 255, 255);
SvgElement el7 = CreateAnElement(false, el6, "", "", "fePointLight",0);
SvgAttribute at22 = CreateAnAttribute(el7, "x", "160", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at23 = CreateAnAttribute(el7, "y", "60", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at24 = CreateAnAttribute(el7, "z", "20", "", SvgAttributeType.Value, "px");
SvgElement el8 = CreateAnElement(false, el5, "", "", "feComposite",0);
SvgAttribute at25 = CreateAnAttribute(el8, "in", "SourceGraphic", "", SvgAttributeType.Text, "px");
SvgAttribute at26 = CreateAnAttribute(el8, "in2", "light", "", SvgAttributeType.Value, "px");
SvgAttribute at27 = CreateAnAttribute(el8, "operator", "arithmetic", "", SvgAttributeType.Text, "px");
SvgAttribute at28 = CreateAnAttribute(el8, "k1", "1", "", SvgAttributeType.Value, "px");
SvgAttribute at29 = CreateAnAttribute(el8, "k2", "0", "", SvgAttributeType.Value, "px");
SvgAttribute at30 = CreateAnAttribute(el8, "k3", "0", "", SvgAttributeType.Value, "px");
SvgAttribute at31 = CreateAnAttribute(el8, "k4", "0", "", SvgAttributeType.Value, "px");
SvgElement el9 = CreateAnElement(false, el1, "", "", "circle",0);
SvgAttribute at32 = CreateAnAttribute(el9, "cx", "170", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at33 = CreateAnAttribute(el9, "cy", "80", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at34 = CreateAnAttribute(el9, "r", "50", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at35 = CreateAnAttribute(el9, "stroke", "#00ff00", "", SvgAttributeType.Color, "px");
CreateAColor(at35, 0, 255, 0, 255, 0);
SvgAttribute at36 = CreateAnAttribute(el9, "stroke-opacity", "1.0", "", SvgAttributeType.Value, "px");
SvgAttribute at37 = CreateAnAttribute(el9, "stroke-width", "1", "", SvgAttributeType.LengthPercent, "px");
SvgAttribute at38 = CreateAnAttribute(el9, "fill", "#00ff00", "", SvgAttributeType.Color, "px");
CreateAColor(at38, 0, 255, 0, 255, 0);
SvgAttribute at39 = CreateAnAttribute(el9, "fill-opacity", "1.0", "", SvgAttributeType.Value, "px");
SvgAttribute at40 = CreateAnAttribute(el9, "filter", "url(#lightMe1)", "", SvgAttributeType.Text, "px");
SvgElement el10 = CreateAnElement(false, el1, "", "feDistantLight", "text",0);
SvgAttribute at41 = CreateAnAttribute(el10, "x", "280", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at42 = CreateAnAttribute(el10, "y", "22", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at43 = CreateAnAttribute(el10, "text-anchor", "middle", "", SvgAttributeType.Text, "px");
SvgElement el11 = CreateAnElement(false, el1, "lightMe2", "", "filter",0);
SvgAttribute at44 = CreateAnAttribute(el11, "id", "lightMe2", "", SvgAttributeType.Value, "px");
SvgElement el12 = CreateAnElement(false, el11, "", "", "feDiffuseLighting",0);
SvgAttribute at45 = CreateAnAttribute(el12, "in", "SourceGraphic", "", SvgAttributeType.Text, "px");
SvgAttribute at46 = CreateAnAttribute(el12, "result", " light", "", SvgAttributeType.Value, "px");
SvgAttribute at47 = CreateAnAttribute(el12, "lighting-color", "#ffffff", "", SvgAttributeType.Color, "px");
CreateAColor(at47, 0, 255, 255, 255, 255);
SvgElement el13 = CreateAnElement(false, el12, "", "", "feDistantLight",0);
SvgAttribute at48 = CreateAnAttribute(el13, "elevation", "20", "", SvgAttributeType.Value, "px");
SvgAttribute at49 = CreateAnAttribute(el13, "azimuth", "240", "", SvgAttributeType.Value, "px");
SvgElement el14 = CreateAnElement(false, el11, "", "", "feComposite",0);
SvgAttribute at50 = CreateAnAttribute(el14, "in", "SourceGraphic", "", SvgAttributeType.Text, "px");
SvgAttribute at51 = CreateAnAttribute(el14, "in2", "light", "", SvgAttributeType.Value, "px");
SvgAttribute at52 = CreateAnAttribute(el14, "operator", "arithmetic", "", SvgAttributeType.Text, "px");
SvgAttribute at53 = CreateAnAttribute(el14, "k1", "1", "", SvgAttributeType.Value, "px");
SvgAttribute at54 = CreateAnAttribute(el14, "k2", "0", "", SvgAttributeType.Value, "px");
SvgAttribute at55 = CreateAnAttribute(el14, "k3", "0", "", SvgAttributeType.Value, "px");
SvgAttribute at56 = CreateAnAttribute(el14, "k4", "0", "", SvgAttributeType.Value, "px");
SvgElement el15 = CreateAnElement(false, el1, "", "", "circle",0);
SvgAttribute at57 = CreateAnAttribute(el15, "cx", "280", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at58 = CreateAnAttribute(el15, "cy", "80", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at59 = CreateAnAttribute(el15, "r", "50", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at60 = CreateAnAttribute(el15, "stroke", "#00ff00", "", SvgAttributeType.Color, "px");
CreateAColor(at60, 0, 255, 0, 255, 0);
SvgAttribute at61 = CreateAnAttribute(el15, "stroke-opacity", "1.0", "", SvgAttributeType.Value, "px");
SvgAttribute at62 = CreateAnAttribute(el15, "stroke-width", "1", "", SvgAttributeType.LengthPercent, "px");
SvgAttribute at63 = CreateAnAttribute(el15, "fill", "#00ff00", "", SvgAttributeType.Color, "px");
CreateAColor(at63, 0, 255, 0, 255, 0);
SvgAttribute at64 = CreateAnAttribute(el15, "fill-opacity", "1.0", "", SvgAttributeType.Value, "px");
SvgAttribute at65 = CreateAnAttribute(el15, "filter", "url(#lightMe2)", "", SvgAttributeType.Text, "px");
SvgElement el16 = CreateAnElement(false, el1, "", "feSpotLight", "text",0);
SvgAttribute at66 = CreateAnAttribute(el16, "x", "390", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at67 = CreateAnAttribute(el16, "y", "22", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at68 = CreateAnAttribute(el16, "text-anchor", "middle", "", SvgAttributeType.Text, "px");
SvgElement el17 = CreateAnElement(false, el1, "lightMe3", "", "filter",0);
SvgAttribute at69 = CreateAnAttribute(el17, "id", "lightMe3", "", SvgAttributeType.Value, "px");
SvgElement el18 = CreateAnElement(false, el17, "", "", "feDiffuseLighting",0);
SvgAttribute at70 = CreateAnAttribute(el18, "in", "SourceAlpha", "", SvgAttributeType.Text, "px");
SvgAttribute at71 = CreateAnAttribute(el18, "result", " light", "", SvgAttributeType.Value, "px");
SvgAttribute at72 = CreateAnAttribute(el18, "lighting-color", "#ffffff", "", SvgAttributeType.Color, "px");
CreateAColor(at72, 0, 255, 255, 255, 255);
SvgElement el19 = CreateAnElement(false, el18, "", "", "feSpotLight",0);
SvgAttribute at73 = CreateAnAttribute(el19, "x", "360", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at74 = CreateAnAttribute(el19, "y", "5", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at75 = CreateAnAttribute(el19, "z", "30", "", SvgAttributeType.Value, "px");
SvgAttribute at76 = CreateAnAttribute(el19, "pointsAtX", "390", "", SvgAttributeType.Value, "px");
SvgAttribute at77 = CreateAnAttribute(el19, "pointsAtY", "80", "", SvgAttributeType.Value, "px");
SvgAttribute at78 = CreateAnAttribute(el19, "pointsAtZ", "0", "", SvgAttributeType.Value, "px");
SvgAttribute at79 = CreateAnAttribute(el19, "limitingConeAngle", "20", "", SvgAttributeType.Value, "px");
SvgElement el20 = CreateAnElement(false, el17, "", "", "feComposite",0);
SvgAttribute at80 = CreateAnAttribute(el20, "in", "SourceGraphic", "", SvgAttributeType.Text, "px");
SvgAttribute at81 = CreateAnAttribute(el20, "in2", "light", "", SvgAttributeType.Value, "px");
SvgAttribute at82 = CreateAnAttribute(el20, "operator", "arithmetic", "", SvgAttributeType.Text, "px");
SvgAttribute at83 = CreateAnAttribute(el20, "k1", "1", "", SvgAttributeType.Value, "px");
SvgAttribute at84 = CreateAnAttribute(el20, "k2", "0", "", SvgAttributeType.Value, "px");
SvgAttribute at85 = CreateAnAttribute(el20, "k3", "0", "", SvgAttributeType.Value, "px");
SvgAttribute at86 = CreateAnAttribute(el20, "k4", "0", "", SvgAttributeType.Value, "px");
SvgElement el21 = CreateAnElement(false, el1, "", "", "circle",0);
SvgAttribute at87 = CreateAnAttribute(el21, "cx", "390", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at88 = CreateAnAttribute(el21, "cy", "80", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at89 = CreateAnAttribute(el21, "r", "50", "", SvgAttributeType.LengthPercent, "");
SvgAttribute at90 = CreateAnAttribute(el21, "stroke", "#00ff00", "", SvgAttributeType.Color, "px");
CreateAColor(at90, 0, 255, 0, 255, 0);
SvgAttribute at91 = CreateAnAttribute(el21, "stroke-opacity", "1.0", "", SvgAttributeType.Value, "px");
SvgAttribute at92 = CreateAnAttribute(el21, "stroke-width", "1", "", SvgAttributeType.LengthPercent, "px");
SvgAttribute at93 = CreateAnAttribute(el21, "fill", "#00ff00", "", SvgAttributeType.Color, "px");
CreateAColor(at93, 0, 255, 0, 255, 0);
SvgAttribute at94 = CreateAnAttribute(el21, "fill-opacity", "1.0", "", SvgAttributeType.Value, "px");
SvgAttribute at95 = CreateAnAttribute(el21, "filter", "url(#lightMe3)", "", SvgAttributeType.Text, "px");
     }
}
