rem selectionSelectionAttributesN
rem copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\Svg
rem copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\Svg
rem copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgExternalResourcesRequired.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgExternalResourcesRequired.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgFillrule.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgFillrule.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgFilter.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgFilter.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgFilter​Units.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgFilter​Units.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgGradient​Units.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgGradient​Units.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgImageRendering.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgImageRendering.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgLength​Adjust.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgLength​Adjust.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgMarker​Units.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgMarkerUnits.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgMask​Content​Units.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgMask​Content​Units.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgMaskUnits.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgMaskUnits.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgMode.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgMode.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgOperator.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgOperator.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgOverflow.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgOverflow.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgPaintOrder.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgPaintOrder.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgPatternContentUnits.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgPatternContentUnits.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgPatternUnits.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgPatternUnits.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgPointerEvents.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgPointerEvents.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgPreserve​Alpha.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgPreserve​Alpha.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgPrimitive​Units.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgPrimitive​Units.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgRestart.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgRestart.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgShapeRendering.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgShapeRendering.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgSpread​Method.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgSpread​Method.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgStitchTiles.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgStitchTiles.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgStrokeLinecap.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgStrokeLinecap.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgStrokeLinejoin.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgStrokeLinejoin.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgTextAnchor.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgTextAnchor.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgTextRendering.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgTextRendering.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgVectorEffect.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgVectorEffect.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgVisibility.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgVisibility.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgWritingMode.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgWritingMode.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgXChannelSelector.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgXChannelSelector.xaml.cs

copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml SvgComposition\AttributeControls\SelectionAttributesN\SvgYChannelSelector.xaml
copy SvgComposition\AttributeControls\SelectionAttributes\SvgAccumulate.xaml.cs SvgComposition\AttributeControls\SelectionAttributesN\SvgYChannelSelector.xaml.cs


