rem value
rem copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\Svg
rem copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\Svg

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgElevation.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgElevation.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgExponent.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgExponent.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgK1.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgK1.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgK2.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgK2.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgK3.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgK3.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgK4.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgK4.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgGradient​Transform.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgGradient​Transform.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgKernelMatrix.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgKernelMatrix.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgKey​Splines.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgKey​Splines.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgKey​Times.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgKey​Times.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgAMask.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgAMask.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgLimitingConeAngle.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgLimitingConeAngle.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgMin.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgMin.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgNumOctaves.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgNumOctaves.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgOpacity.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgOpacity.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgPath​Length.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgPath​Length.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgPoints.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgPoints.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgPointsAtX.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgPointsAtX.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgPointsAtY.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgPointsAtY.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgPointsAtZ.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgPointsAtZ.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgRepeatDur.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgRepeatDur.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgScale.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgScale.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgSeed.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgSeed.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgSpecular​Constant.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgSpecular​Constant.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgSpecularExponent.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgSpecularExponent.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgStrokeMiterlimit.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgStrokeMiterlimit.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgAStyle.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgAStyle.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgSurfaceScale.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgSurfaceScale.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgTabindex.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgTabindex.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgTargetX.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgTargetX.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgTargetY.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgTargetY.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgValues.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgValues.xaml.cs

copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml SvgComposition\AttributeControls\ValueAttributesN\SvgZ.xaml
copy SvgComposition\AttributeControls\ValueAttributes\SvgAmplitude.xaml.cs SvgComposition\AttributeControls\ValueAttributesN\SvgZ.xaml.cs
